/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export function setProtection(
  process_handle: ExternalObject<unknown>,
  address: number,
  size: number,
  protection: number,
): number
export function readBuffer(process_handle: ExternalObject<unknown>, address: number, size: number): Buffer
export function writeBuffer(process_handle: ExternalObject<unknown>, address: number, buffer: Buffer): void
export function getProcessModules(process_handle: ExternalObject<unknown>): Array<ModuleInfo>
export function listAllRunningProcesses(): Array<ProcessInfo>
export function openProcessPid(processPid: number): ExternalObject<unknown>
export function openProcessName(processName: string): ExternalObject<unknown>
export function closeProcess(process_handle: ExternalObject<unknown>): void
export function isElevatedProcess(): boolean
export function is64BitProcess(): boolean
export class ModuleInfo {
  name: string
  baseAddress: number
  constructor(name: string, baseAddress: number)
}
export class ProcessInfo {
  processName: string
  processId: number
  constructor(processName: string, processId: number)
}
